<?php

// Run from the project root after adding or changing backoffice routes.
$projectRoot = dirname(__DIR__);
$command = 'cd '.escapeshellarg($projectRoot).' && php artisan route:list --path=admin --json';
$routes = json_decode(shell_exec($command) ?: '', true);

if (! is_array($routes)) {
    fwrite(STDERR, "Não foi possível ler as rotas do backoffice.\n");
    exit(1);
}

$map = [];
foreach ($routes as $route) {
    if (! str_starts_with($route['uri'], 'admin') || ! str_contains($route['action'], '@')) {
        continue;
    }

    $methods = array_values(array_diff(explode('|', $route['method']), ['HEAD']));
    $path = ltrim(substr($route['uri'], strlen('admin')), '/');
    $map[] = [
        'methods' => $methods,
        'path' => $path,
        'action' => '\\'.$route['action'],
    ];
}

$lines = [
    '<?php',
    '',
    '// Generated by scripts/generate-backoffice-api-map.php.',
    'return [',
];
foreach ($map as $route) {
    $methods = '['.implode(', ', array_map(fn ($method) => var_export($method, true), $route['methods'])).']';
    $lines[] = '    ['.$methods.', '.var_export($route['path'], true).', '.var_export($route['action'], true).'],';
}
$lines[] = '];';
$content = implode("\n", $lines)."\n";
file_put_contents($projectRoot.'/routes/backoffice-api-map.php', $content);
echo 'Mapeadas '.count($map)." rotas de backoffice.\n";
