@extends('layouts.admin')
@section('content')
<div class="card"><div class="card-header">Ficha de pintura #{{ $job->id }} <span class="label label-{{ $job->status === 'completed' ? 'success' : 'warning' }}">{{ \App\Models\PaintingJob::STATUS_SELECT[$job->status] }}</span>
@can('painting_job_edit')<a class="btn btn-info pull-right" href="{{ route('admin.painting-jobs.edit', $job) }}">Editar</a>@endcan</div><div class="card-body">
<div class="row"><div class="col-md-3"><strong>Cliente/contacto</strong><p>{{ $job->client_contact ?: '—' }}</p></div><div class="col-md-3"><strong>Marca/modelo</strong><p>{{ $job->brand_model ?: '—' }}</p></div><div class="col-md-2"><strong>Matrícula</strong><p>{{ $job->license ?: '—' }}</p></div><div class="col-md-2"><strong>Entrada</strong><p>{{ optional($job->entry_date)->format('d/m/Y') }}</p></div><div class="col-md-2"><strong>Saída</strong><p>{{ optional($job->exit_date)->format('d/m/Y') ?: '—' }}</p></div></div>
<p><strong>Operador:</strong> {{ $job->painter?->name ?: 'Por atribuir' }}</p>
</div></div>
<div class="row"><div class="col-md-6"><div class="card"><div class="card-header">Danos a tratar</div><div class="card-body"><table class="table table-bordered"><thead><tr><th>Zona</th><th>Intensidade</th></tr></thead><tbody>@php($damageMap=$job->damages->pluck('intensity','zone'))@foreach(\App\Models\PaintingJob::DAMAGE_ZONES as $zone=>$label)<tr><td>{{ $label }}</td><td>{{ \App\Models\PaintingJob::INTENSITY_SELECT[$damageMap[$zone] ?? ''] ?? '—' }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="col-md-6"><div class="card"><div class="card-header">Materiais</div><div class="card-body"><table class="table table-bordered"><thead><tr><th>Material</th><th>Ref.</th><th>Qtd.</th><th>Data</th><th>Horas</th></tr></thead><tbody>@foreach($job->materials as $item)<tr><td>{{ $item->material_type }}</td><td>{{ $item->reference ?: '—' }}</td><td>{{ $item->quantity ?? '—' }}</td><td>{{ optional($item->used_date)->format('d/m/Y') ?: '—' }}</td><td>{{ $item->hours ?? '—' }}</td></tr>@endforeach</tbody></table></div></div></div></div>
<div class="card"><div class="card-header">Complementos</div><div class="card-body"><div class="row">@foreach(['optics'=>'Óticas','black_parts'=>'Pretos','wheels'=>'Jantes','other_work'=>'Outros'] as $field=>$label)<div class="col-md-6"><strong>{{ $label }}</strong><p>{{ $job->$field ?: '—' }}</p></div>@endforeach</div><strong>Observações</strong><p>{{ $job->notes ?: '—' }}</p></div></div>
@if($job->status === 'open')@can('painting_job_complete')<form method="POST" action="{{ route('admin.painting-jobs.complete',$job) }}" style="display:inline">@csrf<button class="btn btn-success">Concluir ficha</button></form>@endcan @else @can('painting_job_reopen')<form method="POST" action="{{ route('admin.painting-jobs.reopen',$job) }}" style="display:inline">@csrf<button class="btn btn-warning">Reabrir ficha</button></form>@endcan @endif
<a class="btn btn-default" href="{{ route('admin.painting-jobs.index') }}">Voltar</a>
@endsection
