@php($item = $intervention)
<div class="row">
    <div class="col-md-4 form-group {{ $errors->has('repair_id') ? 'has-error' : '' }}"><label class="required">Intervenção / Viatura</label><select class="form-control select2" name="repair_id" required><option value="">Selecione por favor</option>@foreach($repairs as $id => $label)<option value="{{ $id }}" {{ (string) old('repair_id', $selectedRepairId) === (string) $id ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select>@if($errors->has('repair_id'))<span class="help-block">{{ $errors->first('repair_id') }}</span>@endif</div>
    <div class="col-md-4 form-group {{ $errors->has('type_id') ? 'has-error' : '' }}"><label class="required">Tipo</label><select class="form-control" name="type_id" required><option value="">Selecione por favor</option>@foreach($types as $id => $name)<option value="{{ $id }}" {{ (string) old('type_id', $item?->type_id) === (string) $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select>@if($errors->has('type_id'))<span class="help-block">{{ $errors->first('type_id') }}</span>@endif</div>
    <div class="col-md-4 form-group {{ $errors->has('status') ? 'has-error' : '' }}"><label class="required">Estado</label>@if($item)<select class="form-control" name="status" required>@foreach(App\Models\WorkshopIntervention::STATUS_SELECT as $key => $label)<option value="{{ $key }}" {{ old('status', $item->status) === $key ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select>@else<input type="hidden" name="status" value="planned"><input class="form-control" value="Planeado" disabled>@endif @if($errors->has('status'))<span class="help-block">{{ $errors->first('status') }}</span>@endif</div>
</div>
<div class="row">
    <div class="col-md-6 form-group {{ $errors->has('title') ? 'has-error' : '' }}"><label class="required">Título</label><input class="form-control" name="title" value="{{ old('title', $item?->title) }}" required>@if($errors->has('title'))<span class="help-block">{{ $errors->first('title') }}</span>@endif</div>
    <div class="col-md-3 form-group {{ $errors->has('planned_start_date') ? 'has-error' : '' }}"><label class="required">Data inicial</label><input class="form-control" type="date" name="planned_start_date" value="{{ old('planned_start_date', $item?->planned_start_date?->format('Y-m-d') ?: now()->toDateString()) }}" required>@if($errors->has('planned_start_date'))<span class="help-block">{{ $errors->first('planned_start_date') }}</span>@endif</div>
    <div class="col-md-3 form-group {{ $errors->has('planned_end_date') ? 'has-error' : '' }}"><label class="required">Data final</label><input class="form-control" type="date" name="planned_end_date" value="{{ old('planned_end_date', $item?->planned_end_date?->format('Y-m-d') ?: now()->toDateString()) }}" required>@if($errors->has('planned_end_date'))<span class="help-block">{{ $errors->first('planned_end_date') }}</span>@endif</div>
</div>
<div class="form-group {{ $errors->has('mechanic_ids') ? 'has-error' : '' }}"><label class="required">Mecânicos</label><select class="form-control select2" name="mechanic_ids[]" multiple required>@php($selectedMechanics = collect(old('mechanic_ids', $item?->mechanics?->pluck('id')->all() ?: []))->map(fn($id) => (string) $id)->all())@foreach($mechanics as $id => $name)<option value="{{ $id }}" {{ in_array((string) $id, $selectedMechanics, true) ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select>@if($errors->has('mechanic_ids'))<span class="help-block">{{ $errors->first('mechanic_ids') }}</span>@endif</div>
<div class="form-group"><label>Descrição</label><textarea class="form-control" name="description" rows="5">{{ old('description', $item?->description) }}</textarea></div>
<button class="btn btn-danger" type="submit">Gravar</button>
